# Generated by Django 5.2 on 2025-04-20 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('job_applied_for', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSlots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('interviewer_name', models.CharField(max_length=100)),
                ('job_role', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('available', 'Available'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='available', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Interview_Scheduler_app.applicants')),
                ('interview_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Interview_Scheduler_app.interviewslots')),
            ],
        ),
    ]
