# Generated by Django 5.2 on 2025-04-20 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Interview_Scheduler_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Applicants',
            new_name='Applicant',
        ),
        migrations.RenameModel(
            old_name='Assignments',
            new_name='Assignment',
        ),
        migrations.RenameModel(
            old_name='InterviewSlots',
            new_name='InterviewSlot',
        ),
    ]
